import jsmain from "./parser.js";
import { performance } from "perf_hooks";

const str = `for (const T; r * B + d * t; A) 
i + A + a * t + A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t

+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a .* t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t
+ a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t+ A + a * t;`;


{

    const ts = performance.now();
    const result = jsmain(".id{}");
    const te = performance.now();
    console.dir(result, { depth: null });
    console.log(te - ts);
}
{

    const ts = performance.now();
    const result = jsmain(".id{}");
    const te = performance.now();
    console.dir(result, { depth: null });
    console.log(te - ts);
}
{

    const ts = performance.now();
    const result = jsmain(".id{}");
    const te = performance.now();
    console.dir(result, { depth: null });
    console.log(te - ts);
}
{

    const ts = performance.now();
    const result = jsmain(".id{}");
    const te = performance.now();
    console.dir(result, { depth: null });
    console.log(te - ts);
}
{

    const ts = performance.now();
    const result = jsmain(".id{}");
    const te = performance.now();
    console.dir(result, { depth: null });
    console.log(te - ts);
}